[workspace]
members = [
    "programs/*"
]
resolver = "2"

[profile.release]
overflow-checks = false
lto = "fat"
codegen-units = 1
opt-level = "s"
[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1
