/**
 * PDA Utilities - Simplified for Backend-Only Approach
 * 
 * Only contains config PDA generation since that's the only PDA
 * the frontend needs to generate. All note and reaction PDAs
 * are generated by the backend.
 */

import { PublicKey } from '@solana/web3.js';
import { TELLIT_PROGRAM_ID, CONFIG_SEED } from '../constants/programConfig';

/**
 * Get the config PDA
 * This is the only PDA the frontend generates
 */
export function getConfigPda(): [PublicKey, number] {
  return PublicKey.findProgramAddressSync(
    [Buffer.from(CONFIG_SEED)],
    TELLIT_PROGRAM_ID
  );
}
